### ISSUE TITLE
add heroku user to plugin

### ISSUE THREAD

**Issue by dickeyxxx** [heroku/heroku-pipelines#12]
just in case someone needs to push a patch, it would be good to add the shared heroku account as a collab: https://www.npmjs.com/~heroku

**Comment by appleton** [comment]
Thanks for the push and sorry for the delay!
![screen shot 2015-12-08 at 10 01 55](https://cloud.githubusercontent.com/assets/241576/11652963/ba0e09da-9d92-11e5-8f33-8675b90eb3e5.png)

**Comment by gudmundur** [comment]
:+1:
