### ISSUE TITLE
Fails silently with paranoid apps

### ISSUE THREAD

**Issue by neilmiddleton** [heroku/heroku-pipelines#23]
```
$ h pipelines:promote -a paranoid-app-staging
Fetching app info... done
Fetching apps from paranoid-app... done
Starting promotion to production... !
Two-factor code: ********************************************
Fetching app info... done
Fetching apps from paranoid-app... done
Starting promotion to production... done
Waiting for promotion to complete... done

Promotion successful
```

Seems to require preauth first to work.

**Comment by appleton** [comment]
This should now be addressed. @neilmiddleton would you mind giving it a quick check to confirm?

**Comment by neilmiddleton** [comment]
I now get asked for a 2fa.  I assume this is the preauth at work?

**Comment by appleton** [comment]
It ought to be yes. If you supply the 2fa code does it work as expected?

**Comment by neilmiddleton** [comment]
I'll let you know when I can deploy.

**Comment by neilmiddleton** [comment]
Actually.  Yes this is fine :tada:

**Comment by appleton** [comment]
cc @gudmundur another happy customer

**Comment by gudmundur** [comment]
YAY! Thanks for testing and reporting @neilmiddleton!
