### ISSUE TITLE
pipelines:info does not honor the pipeline name parameter

### ISSUE THREAD

**Issue by redbugz** [heroku/heroku-pipelines#35]
According to the docs, I can do:

`heroku pipelines:info <pipeline_name>`

Which has been working fine for us, but suddenly today I get a scrollable list of dates that looks like this:
```
$ heroku pipelines:info example-pipeline
? Which example-pipeline pipeline? (Use arrow keys)
❯ Thu Oct 22 2015 07:33:31 GMT-0600 (MDT) 
  Thu Oct 22 2015 07:34:30 GMT-0600 (MDT) 
  Mon Jul 27 2015 06:04:10 GMT-0600 (MDT) 
  Thu Oct 22 2015 07:51:22 GMT-0600 (MDT) 
  Thu Oct 22 2015 08:13:02 GMT-0600 (MDT) 
  Thu Oct 22 2015 07:38:28 GMT-0600 (MDT) 
  Thu Oct 22 2015 07:36:34 GMT-0600 (MDT) 
(Move up and down to reveal more choices)
```
First none of these dates are helpful to me, and second, when I pick one, it is not the "example-pipeline" that asked for, it is a completely different pipeline.

**Comment by gudmundur** [comment]
In the last few days, we've been transitioning how calls are proxied to the the backend service for pipelines. It seems that in the process, we missed parsing the `?eq[name]=example-pipeline` bit from filtering pipelines by name. The results you are getting back are all of the pipelines you've got access to, you can see that by running `HEROKU_DEBUG=1 heroku pipeliens:info example-pipeline`.

I'm currently working on a fix for this issue, and I expect it to be deployed in the next couple of hours. Thanks for reporting this, and I'll give you an update when it's fixed.

**Comment by appleton** [comment]
Thanks so much for reporting this @redbugz, we've now deployed the fix.
