### ISSUE TITLE
pipelines:promote expected behavior?

### ISSUE THREAD

**Issue by findandrew** [heroku/heroku-pipelines#45]
I have a Rails app on heroku right now. I may be making incorrect assumptions here, but I was expecting to be able to promote my staging app to production `heroku pipelines:promote -a STAGING_APP` and rely on my production environment variables to be swapped into place during `rake assets:precompile` on my production server. However, what I am seeing is that after a `pipelines:promote` the assets precompiled on staging are now on production, and are using the staging environment variables instead of production variables.

I found that when I manually deployed my master branch to my production server `rake assets:precompile` runs as expected and my assets are now using production env vars.

Is it recommended to have parity between staging and production env variables when using heroku pipelines? I feel like I may not be using pipelines as intended? Thanks for any clarification :) Also, lmk if there is a better place to ask this question

**Comment by appleton** [comment]
Pipeline promotion takes the compiled code and copies it across to the next environment. If you have an asset build stage which bakes config into the compiled code then unfortunately its not compatible with pipeline promotion.

If you'd like to use promotion you could consider an alternative setup for your app where asset compilation happens in-request. This sounds wasteful but if you couple it with a caching CDN you can have it compile the assets once on your app server the first time you deploy and then be served from the CDN every time after that.

An alternative might be to run `rake assets:precompile` as part of your server startup script but I imagine that could lead to a pretty long boot time.
