### ISSUE TITLE
setup task failing on linking to repo

### ISSUE THREAD

**Issue by jpowell** [heroku/heroku-pipelines#80]
I'm getting the following when running `pipelines:setup`:

```bash
$ heroku pipelines:setup some-app someorg/somerepo -y --org someorg
Creating pipeline... done
Linking to repo... !
 ▸    The `body` option must be a plain Object or Array when the `form` or `json` option is used
```

It seems as though the issue is happening here:
https://github.com/heroku/heroku-pipelines/blob/master/commands/pipelines/setup.js#L308

which leads to here:
https://github.com/heroku/heroku-pipelines/blob/master/lib/kolkrabbi-api.js#L26

I don't know if the issue is dependency version incompatibility or if one of the components isn't returning an expected value.

**Comment by wadewegner** [comment]
I've seen the exact error. Prevents the ability to fully script the setup of a pipelines.

**Comment by raulb** [comment]
Thanks for reporting. This will be fixed on https://github.com/heroku/heroku-pipelines/pull/82.

**Comment by jpowell** [comment]
Awesome! I was doing a lunch and learn on our tooling that we've written around Heroku CLI, and this wasn't working...

Thanks @raulb & @bigkevmcd
